env:
  browser: true
  es2021: true

extends: eslint:recommended
  
overrides: []

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules: {
  "import/no-extraneous-dependencies": ["error", {"devDependencies": false, "optionalDependencies": false, "peerDependencies": false}],
  "import/extensions": [
      "error",
      "ignorePackages",
      {
        "js": "never",
        "jsx": "never",
        "ts": "never",
        "tsx": "never"
      }
   ]
}
