name: linter
run-name: Lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm init @eslint/config
      - run: npm install eslint-plugin-import --save-dev
      - run: make lint
